### PR TITLE
Fix breakpoints out of order and confusing VSCode

### LINKED ISSUE #215: Breakpoint setting problem
Hi, there is a breakpoint setting problem.

You can see the gif:

### PR DESCRIPTION
**Pull request by Razoric480**
It appears that the way VSCode determines what breakpoint is toggled is via a sorted array of IDs instead of line numbers, so the arguments that the setBreakpointRerquests would send were not guaranteed to be in order.

Fixes #215

### CODE REVIEW

File: src/debugger/debug_session.ts [hunk 1]
```diff
@@ -302,6 +302,7 @@ export class GodotDebugSession extends LoggingDebugSession {
 			});
 
 			bps = this.debug_data.get_breakpoints(path);
+			bps.sort((a, b) => (a.line < b.line ? -1 : 1));
```
Comment (Calinou) [inline src/debugger/debug_session.ts:305]:
```suggestion
			// Sort to ensure breakpoints aren't out-of-order, which would confuse VS Code.
			bps.sort((a, b) => (a.line < b.line ? -1 : 1));
```

**Review by Calinou — APPROVED** [review]
Thanks!
